shakeBake/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'site_info/home'
  root to: 'site_info#home'
  get 'site_info/about' => '/about'

  get 'pairing/query' 
  
  resources :pairing
  
  

end

shakeBake/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

shakeBake/app/models/bread.rb
class Bread < ApplicationRecord
end

shakeBake/app/models/drink.rb
class Drink < ApplicationRecord
end

shakeBake/app/models/pair.rb
class Pair < ApplicationRecord
end

shakeBake/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

shakeBake/app/controllers/pairing_controller.rb
class PairingController < ApplicationController
  def new
    @pair = Pair.new
  end
  
  def show
    @pair = Pair.find(params[:id])
  end
  
  def query
    @query = Pair.find_by_sql("SELECT * FROM pairs WHERE \'#{params[:drinks]}\' == drink AND \'#{params[:breads]}\' == bread;")
    if @query.blank?
      redirect_to :action => "new", :drink => params[:drinks], :bread => params[:breads]
    else
      redirect_to :action => "show", :id => @query[0]['id']
    end
  end
  
  def index
    @drinks = Drink.pluck(:name)
    @breads = Bread.pluck(:name)
  end

  def create
    @pair = Pair.new(pairs_params)

    if @pair.save
      redirect_to pairing_index_path
    else
      render 'new'
    end
  end
  
  def update
  end

  def destroy
  end
  
  private
    def pairs_params
        params.require(:pair).permit(:drink,:bread,:desc)
    end
end

shakeBake/app/controllers/site_info_controller.rb
class SiteInfoController < ApplicationController
  def home
  end
  
end

shakeBake/app/helpers/application_helper.rb
module ApplicationHelper
end

shakeBake/app/helpers/breads_helper.rb
module BreadsHelper
end

shakeBake/app/helpers/drinks_helper.rb
module DrinksHelper
end

shakeBake/app/helpers/pairing_helper.rb
module PairingHelper
end

shakeBake/app/helpers/pairs_helper.rb
module PairsHelper
end

shakeBake/app/helpers/site_info_helper.rb
module SiteInfoHelper
end

shakeBake/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShakeBake</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

shakeBake/app/views/pairing/_drink-list.html.erb
<div class="list-container">
  <%= form_for @pairs do |f| %>
    <div id="drink_lists">
      <%=  @drinks.each do |val| %>
        <%= f.radio_button("drinks", "option", val, :class => list-item) %>
      <% end %>
    </div>
    <div id="bread_list">
      <%=  @breads.each do |val| %>
        <%= f.radio_button("breads", "option", val, :class => list-item) %>
      <% end %>
    </div>
    <%= f.submit "Find my Pairing!" id="submit_button" %>
  <% end %>
</div>

shakeBake/app/views/pairing/_footer.html.erb
<footer class="stopper center">
  <p>&copy; Shakers and Bakers</p>
</footer>

shakeBake/app/views/pairing/_header.html.erb
<header class="stopper center">
  <h2>Shakers and Bakers</h2>
  <nav>
    <ul>
      <li><%= link_to "HOME", site_info_home_path %>   
      <li><%= link_to "PAIRS", pairing_index_path %>   
      <li><%= link_to "CONTACT", site_info_contact_path %>   
      <li><%= link_to "ABOUT", site_info_about_path %>
    </ul>
  </nav>
</header>

shakeBake/app/views/pairing/_list-form.html.erb
<div class="list-container">
  <%= form_tag(pairing_query_path, method: :get) do %>
    <div id="drink_lists">
      <%  @drinks.each do |val| %>
      <%= puts val %>
        <%= radio_button_tag("drinks", val, false, :class => "list-item", :id => "list-item-#{val.tr(" ", "-")}", :required => "") %> <p class="item-value"><%= val %></p>
      <% end %>
    </div>
    <div id="bread_list">
      <%  @breads.each do |val| %>
        <%= radio_button_tag("breads", val, false, :class => "list-item", :id => "list-item-#{val.tr(" ", "-")}", :required => "") %> <p class="item-value"><%= val %></p>
      <% end %>
    </div>
    <div class="submit_div">
      <br>
    <%= submit_tag("Find my Pairing!", :class => "submit_button") %>
    </div>
  <% end %>
  <br><br>
</div>

shakeBake/app/views/pairing/index.html.erb
<div id="main">
  <title>Pairings</title>
    <%= link_to '<-- Home', site_info_home_path, :style => "text-decoration: underline; color: black; font-weight: bold; font-family: sans-serif;" %>
    
    <div class="center">
    <%= image_tag("logo2.png", :alt => "logo", :size => "150x150", :style => "display: inline;") %>
    </div>
    <h1>Pairings</h1>

    <%= render "list-form" %>

</div>

shakeBake/app/views/pairing/new.html.erb
<div id="main">
    <%= link_to '<-- Home', site_info_home_path, :style => "text-decoration: underline; color: black; font-weight: bold; font-family: sans-serif;" %>
    
    <div class="center">
    <%= image_tag("logo2.png", :alt => "logo", :size => "150x150", :style => "display: inline;") %>
    <h1>Create a Pairing</h1>

    <%= form_for @pair, url: pairing_index_path do |f| %>
      <div class="hidden_fields">
        <%= f.hidden_field(:drink, :value => params[:drink]) %>
        <%= f.hidden_field(:bread, :value => params[:bread]) %>
      </div>
      <hr>
      <div class="text_field">
        <%= f.label :desc, "Description: "%><br><br>
        <%= f.text_area :desc, :class => "textarea1", :placeholder => "Type your description here..." %>
      </div>
      <br>
      <div id="submission">
        <%= f.submit :class => "nav1" %>
      </div>

    <% end %>
</div>
</div>

shakeBake/app/views/pairing/show.html.erb
<div id="main">
    <%= link_to '<-- Home', site_info_home_path, :style => "text-decoration: underline; color: black; font-weight: bold; font-family: sans-serif;" %>
    
    <div class="center">
    <%= image_tag("logo2.png", :alt => "logo", :size => "150x150", :style => "display: inline;") %>
    <h1><span class="spec"><%= @pair.drink %></span> and <span class="spec"><%= @pair.bread %></span></h1>
    <hr>
    <h2>Pairing Description:</h2>
    <br>
    <div class="box">
    <p class="descbox1">" </p>
    <p class="descbox">
      <%= @pair.desc %>
    </p>
    <p class="descbox1"> "</p>
    </div>
    </div>
</div>

shakeBake/app/views/site_info/about.html.erb
<div id="main">
  <br>
    <%= link_to '<-- Home', site_info_home_path, :style => "text-decoration: underline; color: black; font-weight: bold; font-family: sans-serif;" %>
    <div class="center">
      <%= image_tag("logo2.png", :alt => "logo", :size => "150x150", :style => "display: inline;") %>
    </div>
    <h1>About US</h1>
    <div class="center">
      <p id="about">
        WE ... ARE ... SHAKEBAKE. A team of five fervourous coders and masterminds. We have brought the world the all-time best
        software for ensuring that your bread and drink pairings needs are met. Our goal was to bring you a piece of software
        to revolutionize the way you fulfill your epicurean needs.
      </p>
      <%= image_tag("company_photo.png", :alt => "shakebake-members", :style => "display: inline;", :class => "group_pic") %>
  </div>
</div>

shakeBake/app/views/site_info/home.html.erb
    <div id="main">
    <br>
    <div class="center">
    <%= image_tag("logo2.png", :alt => "logo", :size => "150x150", :style => "display: inline;") %>
    </div>
    <h1>Home</h1>
    <div class="center">
    <p id="mission">" We here at Shakers and Bakers believe in providing the most luscious, unparalleled drink and bread pairings on the market.<br>All your tireless searching for the perfect drunk match is FINALLY over.  This is the only website you will EVER need again. "</p>
    <br><br>
    <%= link_to 'Search for a Drink/Bread Pairing', pairing_index_path, :class => 'nav' %>
    <br><br>
    <%= link_to 'About ShakeBake', site_info_about_path, :class => 'nav button2' %>
    </div>
    </div>